@baseUrl = http://localhost:8000/api/users

### GET ALL RECEIVED & SENT BOOKINGS OF A USER
GET {{baseUrl}}/67d9787538abedcfa89660f3/bookings

### GET ONLY RECEIVED BOOKINGS OF A USER
GET {{baseUrl}}/67d9787538abedcfa89660f3/bookings/received

### GET ONLY SENT BOOKINGS OF A USER
GET {{baseUrl}}/67d9787538abedcfa89660f3/bookings/sent