@baseUrl = http://localhost:8000/api/users/favourites

### ADD ARTIST/VENUE TO FAVOURITES
POST {{baseUrl}}
Content-Type: application/json


{
  "favouriteId":"67dc1052fc23ef9f183ed166"
}

### REMOVE ARTIST/VENUE FROM FAVOURITES
DELETE {{baseUrl}}/67d9787538abedcfa89660f3

### GET ALL FAVOURITED ARTISTS
GET {{baseUrl}}
