export const REVENUE_SPLIT_OPTIONS = [
  "100/0",
  "90/10",
  "80/20",
  "70/30",
  "60/40",
  "50/50",
];

export const ARTIST_PERFORMANCE_TYPES = {
  "Musical Acts": [
    "Band",
    "Duo",
    "Solo Artist",
    "Singer-Songwriter",
    "Rapper",
    "DJ",
    "Orchestra",
    "Ensemble",
  ],
  "Performing Acts": [
    "Dancer",
    "Comedian",
    "Poet",
    "Spoken Word Artist",
    "Magician",
    "Theatrical Performer",
    "Drag Performer",
    "Improv Performer",
  ],
  Other: [
    "Digital Artist",
    "Multi-disciplinary Artist",
    "Performance Collective",
    "Other",
  ],
};

export const ARTIST_GENRES = {
  "Music Genres": [
    "Alternative",
    "Art Pop",
    "Blues",
    "Classical",
    "Country",
    "Dance",
    "Disco",
    "Dream Pop",
    "EDM",
    "Electronic",
    "Experimental",
    "Folk",
    "Folk Rock",
    "Funk",
    "Garage Rock",
    "Hip Hop",
    "Indie",
    "Indie Pop",
    "Indie Rock",
    "Jazz",
    "Latin",
    "Metal",
    "Pop",
    "Psychedelic Rock",
    "Punk",
    "Reggae",
    "Rock",
    "R&B",
    "Soul",
    "World Music",
  ],
  "Dance Styles": [
    "Ballet",
    "Ballroom",
    "Break Dance",
    "Contemporary",
    "Hip Hop Dance",
    "Jazz Dance",
    "Modern Dance",
    "Street Dance",
    "Tap",
    "Traditional Dance",
  ],
  "Comedy & Spoken Word": [
    "Improv Comedy",
    "Slam Poetry",
    "Stand-up",
    "Traditional Poetry",
  ],
  "Performance Arts": [
    "Theater",
    "Burlesque",
    "Cabaret",
    "Digital Performance",
    "Drag",
    "Magic",
  ],
  Other: ["Adult", "Family-Friendly", "Other"],
};

export const VENUE_TYPES = [
  "Bar",
  "Jazz Bar",
  "Club",
  "Concert Hall",
  "Arena",
  "Comedy Club",
  "Cabaret Club",
  "Outdoor Venue",
  "Rooftop Venue",
  "Festival",
  "Theater",
  "Cultural Center",
  "Community Center",
  "Café",
  "Restaurant",
  "Hotel",
  "Art Gallery",
  "Museum",
  "Co-working Space",
  "Bookstore",
  "Pop-up Space",
  "Other",
];
