@baseUrl = http://localhost:8000/api/auth

### REGISTER A NEW USER
POST {{baseUrl}}/register
Content-Type: application/json

{
  "firstName":"Evie",
  "lastName":"Wilcock",
  "email":"eviewilcock01@gmail.com",
  "password":"123456",
  "role":"artist"  
}

### VERIFY REGISTERED USER'S EMAIL
GET {{baseUrl}}/verify-email

### LOGIN A USER
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email":"phoebe@example.com",
  "password":"123456"
}


### LOGOUT A USER
GET {{baseUrl}}/logout

### GET USER AUTH DATA
GET {{baseUrl}}/user-data

### UPDATE USER AUTH DATA
PATCH {{baseUrl}}/update-account
Content-Type: application/json

{
  "firstName":"Test",
  "lastName":"Venue"
}

### CHANGE PASSWORD
PATCH {{baseUrl}}/change-password
Content-Type: application/json

{
  "currentPassword":"123456",
  "newPassword":"1234567"
}

### DELETE USER ACCOUNT AND ALL RELATED DATA
DELETE {{baseUrl}}/delete-account

