@baseUrl = http://localhost:8000/api/bookings

### REQUEST AN ARTIST OR VENUE
POST {{baseUrl}}
Content-Type: application/json

{
  "receiverId":"67d9619581fea814fa967a34",
  "performanceDate":"2026-05-01T20:00:00.000Z"
}

### GET A SPECIFIC BOOKING
GET {{baseUrl}}/67dbcf92e04a79c12202717c

### EDIT BOOKING DATE
PATCH {{baseUrl}}/67dbcf92e04a79c12202717c/edit
Content-Type: application/json

{
  "performanceDate":"2025-05-01T20:00:00.000Z"
}

### ACCEPT BOOKING REQUEST
PATCH {{baseUrl}}/67dbcf92e04a79c12202717c/accept
Content-Type: application/json


### DECLINE BOOKING REQUEST
PATCH {{baseUrl}}/67dbcf92e04a79c12202717c/decline
Content-Type: application/json


### CANCEL ACCEPTED BOOKING
PATCH {{baseUrl}}/67dbcf92e04a79c12202717c/cancel
Content-Type: application/json


### GET ALL ACCEPTED BOOKINGS
GET {{baseUrl}}/accepted